            - ชื่อ: แคช
  ใช้: actions/cache@v5.0.1
  กับ:
    # รายชื่อไฟล์ โฟลเดอร์ และรูปแบบตัวอักษรตัวแทน (wildcard) ที่ต้องการแคชและกู้คืน
    เส้นทาง:
    # คีย์ที่ระบุอย่างชัดเจนสำหรับการกู้คืนและบันทึกแคช
    สำคัญ:
    # สตริงหลายบรรทัดเรียงลำดับที่แสดงรายการคีย์ที่ตรงกับคำนำหน้า ซึ่งใช้สำหรับกู้คืนแคชที่ล้าสมัยหากไม่มีการค้นหาในแคชสำหรับคีย์นั้น โปรดทราบว่า `cache-hit` จะส่งคืนค่า false ในกรณีนี้
    restore-keys: # ตัวเลือกเสริม
    # ขนาดส่วนย่อยที่ใช้แบ่งไฟล์ขนาดใหญ่ระหว่างการอัปโหลด (หน่วยเป็นไบต์)
    ขนาดส่วนการอัปโหลด: # ตัวเลือกเสริม
    # ค่าบูลีนเสริม เมื่อเปิดใช้งาน จะอนุญาตให้โปรแกรมรันเนอร์ของ Windows บันทึกหรือกู้คืนแคช ซึ่งสามารถกู้คืนหรือบันทึกได้ตามลำดับบนแพลตฟอร์มอื่นๆ
    enableCrossOsArchive: # ตัวเลือกเสริม ค่าเริ่มต้นคือ false
    # ยกเลิกเวิร์กโฟลว์หากไม่พบรายการในแคช
    fail-on-cache-miss: # ตัวเลือกเสริม ค่าเริ่มต้นคือ false
    # ตรวจสอบว่ามีรายการในแคชสำหรับข้อมูลป้อนเข้าที่กำหนด (คีย์, คีย์กู้คืน) หรือไม่ โดยไม่ต้องดาวน์โหลดแคช
    lookup-only: # ตัวเลือกเสริม ค่าเริ่มต้นคือ false
    # เรียกใช้ขั้นตอนหลังการดำเนินการเพื่อบันทึกแคช แม้ว่าขั้นตอนก่อนหน้าจะล้มเหลวก็ตาม
    save-always: # ตัวเลือกเสริม ค่าเริ่มต้นคือ false
          name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: build 
        run: |
            pnpm install
            pnpm run build
      - name: test
        run: |
             pnpm run test
