name: Publish sunaget/sunhat-dev

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'tag of image(e.g. 0.1.0)'
        required: true
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    environment: release

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sunagent/sunhat-dev
          tags: |
            type=sha,prefix=,suffix=,format=short
            type=raw,value=${{ github.event.inputs.image_tag }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
